Expression ::= Term (('+' | '-') Term )* /* Term | Term '+' Term | Term '-' Term */
Term ::=  Factor (('*' | '/') Factor )* /* Factor | Factor '*' Factor | Factor '/' Factor */
Factor ::= Number | '(' Expression ')'
